# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:math.oc'

# 検索キーワード
keywords:
        kaggle: 1
        Neural network: 1
        GAN: 1
        topoloogy optimization: 2
        topology design: 2
        deep learning: 1
        machine learnig: 1
        data driven: 1
        Topology Optimization: 2
        Deep Learning: 1

# 通知の閾値
score_threshold: 2
