# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:math.oc'

# 検索キーワード
keywords:
        kaggle: 1
        topology: 3
        NN: 2
        GAN: 2
        topoloogy optimization: 3
        machine learnig: 1

# 通知の閾値
score_threshold: 0
