# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:math.oc'

# 検索キーワード
keywords:
        kaggle: 1
        Neural network: 1
        GAN: 1
        topoloogy optimization: 3
        topology design: 3
        deep learning: 1
        machine learnig: 1

# 通知の閾値
score_threshold: 3
